### ISSUE TITLE
Syntax highlighting bug

### ISSUE THREAD

**Issue by Moelf** [JuliaEditorSupport/Julia-sublime#105]
https://github.com/sharkdp/bat/issues/1692#issuecomment-868790160

**Comment by randy3k** [comment]
It is not our issue.
![Screen Shot 2021-06-25 at 6 20 52 PM](https://user-images.githubusercontent.com/1690993/123497387-1a917e80-d5e2-11eb-81f5-3434d512b2d2.png)
