### ISSUE TITLE
Unicode expansion for other file types

### ISSUE THREAD

**Issue by jabirali** [JuliaEditorSupport/Julia-sublime#107]
First, thanks for maintaining this nice plugin :)

The "sister package" [JuliaEditorSupport/julia-vim](https://github.com/JuliaEditorSupport/julia-vim) has a nice feature whereby a config option `g:latex_to_unicode_file_types` can be used to enable tab-expansion of LaTeX codes to Unicode symbols in other file types than just Julia code files:

> ### LaTeX-to-Unicode on other file types
>
> By default, the LaTeX-to-Unicode substitutions are only active when editing Julia files. However, you can use
the variable `g:latex_to_unicode_file_types` to specify for which file types this feature is active by default. The variable must be set to a string containing a pattern (a regular expression) which matches the desired file
types, or to a list of such patterns. For example, to activate the feature on all file types, you could put `let g:latex_to_unicode_file_types = ".*"` in your `.vimrc` file. Be aware, however, that enabling the functionality overrides the `completefunc` setting.

This can be useful if you e.g. write MarkDown documentation of Julia code and wish to refer to the same symbols, or if you use a TeX engine like LuaLaTeX that supports Unicode symbols in math.

Would it be possible to add similar functionality to this plugin? If there's already a simple way to do this, perhaps it can be added to the README file?

**Comment by randy3k** [comment]
Check out https://packagecontrol.io/packages/UnicodeCompletion

Actually the Unicode feature of Julia is adopted from UnicodeCompletion

**Comment by jabirali** [comment]
Perfect, this was what I was looking for :)
