### ISSUE TITLE
`=` changes highlighting depending on spaces?

### ISSUE THREAD

**Issue by ahwillia** [JuliaEditorSupport/Julia-sublime#11]
For example:

<img width="242" alt="screen shot 2016-08-05 at 6 19 51 pm" src="https://cloud.githubusercontent.com/assets/636625/17453859/3a30440c-5b39-11e6-9b6f-348fe176d417.png">

This is when I install the latest through Package Manger with sublime. Not sure if this is already fixed but not on a tagged release? Or is this intentional?

Thanks for your support on this.

**Comment by ViktorQvarfordt** [comment]
We are currently not on tagged releases. This repo just underwent a transfer to https://github.com/JuliaEditorSupport/Julia-sublime, as we update the records in Package Control we will switch to tagged releases, as this is the convention in Package Control.

**Comment by ViktorQvarfordt** [comment]
Now it works. Anyway, is this how we want to highlight types; do we want `::` to be blue as well as the type? Should `::` instead be white, or perhaps red (as an operator)?

**Comment by ahwillia** [comment]
I would say red as an operator. Just my 2 cents. Thanks!
