### ISSUE TITLE
Fix order of match blocks for macro rule

### ISSUE THREAD

**Issue by fsaad** [JuliaEditorSupport/Julia-sublime#110]
I think the order of the `match` blocks for `macros` should be switched here https://github.com/JuliaEditorSupport/Julia-sublime/blob/054fc4afa517b25a1b6c5bd7d968a40b4f35d0be/Julia.sublime-syntax#L351-L361

The current order results in the following highlighting error

![Screenshot at 2021-08-19 14-09-55](https://user-images.githubusercontent.com/5721897/130121850-8d7fc8f6-f2cd-40ea-94b9-b366cc60e35d.png)

where `@time` has been greedly matched to the `time` entry in `base_macros`.

A related issue is that syntax highlighting fails on the built-in macros `@timed` and `@timev`, where the last character is not highlighted, since `time` appears before `timed` and `timev` in the `base_macros` list.

**Comment by jwortmann** [comment]
I think the order cannot be switched here, because in that case base_macros would never match. But an easy fix should be to add a `\b` after `{{base_macros}}` to ensure a word boundary at the end of the identifier.

**Comment by randy3k** [comment]
@jwortmann is right.

**Comment by jwortmann** [comment]
That commit looks still incomplete. `@.` can't match anymore now. It should be like this:
```diff
-     - match: '(@)({{base_macros}}|\.)\b'
+     - match: '(@)({{base_macros}}\b|\.)'
```

**Comment by randy3k** [comment]
Oh, my bad. Will fix it as soon as possible.
