### ISSUE TITLE
Multi-line Comments

### ISSUE THREAD

**Issue by matthieugomez** [JuliaEditorSupport/Julia-sublime#112]
Thanks for the great package. 

I still have an issue with multi-line comment in ST 4
![Screen Shot 2021-08-29 at 9 39 50 AM](https://user-images.githubusercontent.com/6223837/131252427-c7a56b2d-6460-4a28-ade4-c2181767f9ef.jpg)

I think the text and the second line should be the same gray color as the first line (as it was in ST3)

**Comment by randy3k** [comment]
I am pretty sure that it is working.
![Screen Shot 2021-08-29 at 2 13 56 PM](https://user-images.githubusercontent.com/1690993/131265513-8d28d6a8-e5d1-42a8-bb3f-689624dc3a47.png)

**Comment by matthieugomez** [comment]
Thanks for your answer. 
I have checked on my computer and the syntax highlighting is indeed correct when there are 4 equal signs after `#` or less. However, if there are more than four (as in my example), syntax highlighting does not work. Can you reproduce it?
<img width="96" alt="Screen Shot 2021-08-29 at 6 25 09 PM" src="https://user-images.githubusercontent.com/6223837/131267201-723a710b-cd56-4e21-9eda-94c73a86c050.png">

**Comment by randy3k** [comment]
Thanks for reported it. Fixed in v1.0.6.
