### ISSUE TITLE
v 4133 and unicode tab completion

### ISSUE THREAD

**Issue by PaulSoderlind** [JuliaEditorSupport/Julia-sublime#117]
Since sublime was updated to 4133 earlier today (27 May 2022), typing `\alpha[TAB]` gives `\α`. Yes, with the  `\`.

**Comment by randy3k** [comment]
I cannot reproduce your issue though. Tab completion still works for me.

**Comment by PaulSoderlind** [comment]
Thanks. To be sure, I just double checked on several Win10 machines (with Sublime 4134). They all show the same problem. In short,  Tab completion "works" but leaves a `\` at the beginning.

How can I help debug this?

**Comment by PaulSoderlind** [comment]
seems to have been fixed by Sublime 4138
