### ISSUE TITLE
Highlighting functions in UnitRange

### ISSUE THREAD

**Issue by ahwillia** [JuliaEditorSupport/Julia-sublime#14]
This is minor, but I think the colon should be red here on the second line. Happy to keep opening these if they are helpful for you!

<img width="112" alt="screen shot 2016-08-07 at 7 09 16 pm" src="https://cloud.githubusercontent.com/assets/636625/17467382/911660b8-5cd2-11e6-9abd-38da6d195581.png">

**Comment by ViktorQvarfordt** [comment]
Keep 'em coming! Hopefully this commit takes care of everything.
