### ISSUE TITLE
transpose sign problem

### ISSUE THREAD

**Issue by GaborOszlanyi** [JuliaEditorSupport/Julia-sublime#15]
I have noticed the following problem.
Please, could you have a look at it?

``
b = transpose(a)
``
This line does not cause any harm.

``
b = a'
``
But this line switches off syntax highlighting for the code that follows.
Syntax highlighting only comes back after a second transpose sign occurs.

**Comment by ViktorQvarfordt** [comment]
Thanks for opening the issue! And sorry for this bug, I caused this quite recently when I fixed some other things. It should be working now.

**Comment by GaborOszlanyi** [comment]
Wow! This was a really fast fix.
Thank you very much.
