### ISSUE TITLE
Commas are highlighted as part of functions

### ISSUE THREAD

**Issue by ahwillia** [JuliaEditorSupport/Julia-sublime#16]
See the last line here. I think the `x` and the comma should be white. Thanks again -- all your fixes are working for me and are well appreciated 😄 

<img width="85" alt="screen shot 2016-08-08 at 10 28 05 am" src="https://cloud.githubusercontent.com/assets/636625/17489443/ea089c1a-5d52-11e6-86c1-437838791a07.png">

Perhaps it thinks `x,f` is the function name, which should be an easy fix?

<img width="62" alt="screen shot 2016-08-08 at 10 31 51 am" src="https://cloud.githubusercontent.com/assets/636625/17489548/58de18c2-5d53-11e6-8261-5e73e30d9344.png">

**Comment by ViktorQvarfordt** [comment]
Oops, one of the most obvious symbols was left out in the new regex. Easy fix indeed. Thanks!

By the way, I've been pushing lots of commits the last couple of days. Is this noticeable to users via package control? (Other than that the new code actually gets pulled automatically, which I hope it does.)

**Comment by ahwillia** [comment]
I've been going to `Package Control -> Upgrade Packages` and then `Julia` pops right up and I click it. I don't think it automatically updates by default. Certainly nothing intrusive - I would keep committing away. Hopefully users will instinctively try to update when they spot an error.

**Comment by ViktorQvarfordt** [comment]
Great, I was getting worried that I was spamming people. Regarding auto-update, in https://packagecontrol.io/docs/settings it says

> `auto_upgrade`
If packages installed via Package Control should be checked for updates when Sublime Text starts. Updates will be automatically installed.
`Default true`

which is perfect.

By the way, if you're interested, I've started to keep a list of the intended highlighting behavior in the [wiki](https://github.com/JuliaEditorSupport/Julia-sublime/wiki#tests). I just added `x,f(x)` to the list. If you can think of more weird cases, you're welcome to add it to the code snippet and I'll update the image. This is useful for checking that everything works and does not break in the future.
