### ISSUE TITLE
Highlighting nabla + number as a variable name

### ISSUE THREAD

**Issue by ahwillia** [JuliaEditorSupport/Julia-sublime#18]
See the third to last line here:

<img width="98" alt="screen shot 2016-08-09 at 3 47 51 pm" src="https://cloud.githubusercontent.com/assets/636625/17536253/a623f3f4-5e48-11e6-9593-a0f0d1639032.png">

**Comment by ViktorQvarfordt** [comment]
This was an old lurking problem with unicode stuff again. There is *no* word boundary between `β` and `, but there *is* a word boundary between `∇` and 1.

It is an easy fix, but also this will be part of the rewriting I'm doing. It will come soon-ish.

**Comment by ViktorQvarfordt** [comment]
Fixed in #21.
