### ISSUE TITLE
Rewrite Julia.tmLanguage to Julia.sublime-synax

### ISSUE THREAD

**Issue by ViktorQvarfordt** [JuliaEditorSupport/Julia-sublime#21]
The develop branch now contains a rewrite from `Julia.tmLanguage` to `Julia.sublime-synax`. It fixes and improves *a lot* of things.

- Syntax parsing is much easier and flexible, allows for more complex highlighting and easier maintenance.
- Improved syntax highlighting for all sorts of declarations (types, functions, macros). Parameters in function and macro definitions are highlighted.
- String interpolation is highlighted for double quoted strings (without string modifiers, this can of course be enabled for all strings). Do we want this? Check it out.
-  Proper [automated syntax tests](https://www.sublimetext.com/docs/3/syntax.html#testing) in `syntax_test_julia.jl` (Run tests by running the `build` command.)
- `Julia.tmLanguage` will be kept for backward compatibility. The `sublime-syntax` format was introduced in [sublime text build](http://www.sublimetext.com/3dev) 3084 more than a year ago.

Check it out by cloning the repo into `.../sublime_path/Packages/` and checkout `develop`.

Comments, thoughts and reactions to this?

**Comment by GaborOszlanyi** [comment]
Function call highlighting is very useful.
Please keep it.

**Comment by ViktorQvarfordt** [comment]
What's your take on the fact that essentially no other syntax highlighting package does this? It feels weird to deviate from this convention.

However, I do agree with you that it is very useful to have function call highlighting. But it's messy if this is the same color as types. Even though I don't set the syntax scope on function calls so that they are highlighted by default, I do set the standard scope `variable.function` on function calls, so that you can choose to highlight them with your own color theme. In my theme (that is just 5 lines tweaked from a standard theme) I get:

![image](https://cloud.githubusercontent.com/assets/344809/17606274/e51d3714-601e-11e6-9d08-72d520a40a52.png)

A real-world example of where types and function calls would meld if having the same color.

![image](https://cloud.githubusercontent.com/assets/344809/17606548/511b1dd6-6020-11e6-9028-d60072040398.png)

(Note that I'm not very proud of my choice of color for variables and function calls in these pictures, the point is that they're different, and not white.)

**Comment by GaborOszlanyi** [comment]
I can only judge by what I see.
Function call highlighting as a default is better than the "convention".
In case your decide differently, it is good to have the option to switch it back.

Otherwise, I am using the "blackboard" color scheme, and it is great.

**Comment by ViktorQvarfordt** [comment]
It's not "just" a "convention", every sublime-built-in syntax definition does it this way. (And reserve highlighting of functions to language-built-in functions.)

However, my feeling is that people want function calls to be highlighted. Perhaps I'll keep this the way it is. (It is literally just one line in the syntax definition that changes this.)

The picky ones can always get it the way they want by configuring the color theme. The question is what default to use to satisfy most users.

**Comment by GaborOszlanyi** [comment]
It was just my 2 cents.
Also I do appreciate the option to change it.

**Comment by ViktorQvarfordt** [comment]
Much appreciated!

When you say "option to change it", I assume you mean something other than fiddling with the color scheme. I'm not sure such an option can be implemented easily. (Something like loading different syntax files based on a setting would be possible, but also something I'd strive to avoid.)

I think I'll keep function call highlighting the way it is. If the discussion comes up again it is very easy to change it. And in either case it can be controlled from the color scheme.

**Comment by randy3k** [comment]
looking forward to this

**Comment by ViktorQvarfordt** [comment]
I just pushed a commit that puts this in a state at which I'm satisfied. I've tested it on lots of code from `Base` etc. All looks good. Every weird case I could find has a test in `syntax_test_julia.jl`.

I'll let this rest for a while, if nothing else is found I'll merge `develop` into `master`.

**Comment by ViktorQvarfordt** [comment]
I keep highlighting all function calls.

Still up for discussion: Color of macro invocation. Previously this had the same color as function calls. I think it is more appropriate to highlight this the same as keywords (such as `function`, `begin`, `end`, this is how the new code currently behaves. Tell me if I'm wrong. (Another alternative is to highlight macros in another color, maybe the same orange as parameters in function declarations.)

**Comment by GaborOszlanyi** [comment]
The role of macros is closer to functions than to keywords.
So I would prefer:
- the color of macro definitions to be the same as function definitions
- the color of macro invocations to be the same as function calls

**Comment by ViktorQvarfordt** [comment]
You've convinced me, I agree. `develop` now has this behavior. (And as for functions, macros also gets the scope `variable.macro`, so that it is possible to customize the color in ones color theme.) Let me know if there's something more that you think should be changed.

**Comment by ViktorQvarfordt** [comment]
Possible point of discussion: Currently we have ![image](https://cloud.githubusercontent.com/assets/344809/17635040/aa364c78-60d5-11e6-93e7-2f2bf0c8df0b.png) because I highlight something as a type if I can detect that it is a type. It obviously gives an inconsistency . What do we think of this?

I could of course highlight all types exported in `Base`, such as `Array`, but then user-defined types would still end up white. Perhaps this is a good compromise.

**Comment by GaborOszlanyi** [comment]
Thank you for the macro/function consistency.

**Comment by ViktorQvarfordt** [comment]
Np! Also, I realize that it is perhaps best to not highlight types that occur as variables, only highlight types in type annotations. Thoughts?

**Comment by GaborOszlanyi** [comment]
I agree. 
Then let's see how it feels in the long run.

**Comment by ViktorQvarfordt** [comment]
Okay, `develop` now does this.

**Comment by ahwillia** [comment]
> I highlight something as a type if I can detect that it is a type. It obviously gives an inconsistency . What do we think of this?

Seems like we have to live with it. I can't think a way around this.

**Comment by ahwillia** [comment]
Relevant to the macro highlighting discussion:

<img width="175" alt="screen shot 2016-08-12 at 4 58 03 pm" src="https://cloud.githubusercontent.com/assets/636625/17640043/1a746f4c-60ae-11e6-8d11-3eaa30ce85a3.png">

The final line is valid way to call a macro and should be highlighted teal -- i.e. this is not a function definition since the macro will expand first. I generally agree with all comments above about how to handle macro highlighting.

**Comment by ahwillia** [comment]
Another point related to type highlighting:

<img width="195" alt="screen shot 2016-08-12 at 6 23 56 pm" src="https://cloud.githubusercontent.com/assets/636625/17640684/144e61fc-60ba-11e6-8f95-b0756d8773a2.png">

You might consider making the function call take precedence here so that `typeof(myvar)` is not highlighted like a type. I feel like this would be more consistent with how the Modules are highlighted (see https://github.com/JuliaEditorSupport/Julia-sublime/issues/19)

**Comment by ViktorQvarfordt** [comment]
Good one with the macro! I've pushed a fix to `develop`, which also fixes "macro interpolation" to ordinary function declaraions:

![image](https://cloud.githubusercontent.com/assets/344809/17641100/d5de492e-6112-11e6-8f05-b0fe0ca0b2b2.png)

**Regarding function calls inside type:** I don't necessarily disagree, but this opens up for inconsistencies:

![image](https://cloud.githubusercontent.com/assets/344809/17641190/c6bbfd6c-6115-11e6-9534-86b5dd6da04e.png)

Thoughts? My take on this is that we do not change it. I think that type annotations will be close to unreadable if colors are changed too much, we already have a lot going on with the colors. Consider this real-world example:

![image](https://cloud.githubusercontent.com/assets/344809/17641210/587ae3d0-6116-11e6-947f-ab398f5730e5.png)

---

By the way, just so that we're on the same page: I didn't go with what was suggested in #19. Instead we have

![image](https://cloud.githubusercontent.com/assets/344809/17641067/a23bce9e-6111-11e6-92ee-1979ce69a36f.png)

**Comment by ahwillia** [comment]
Yes - I think you were right on #19. I also agree leaving the function calls as is within curly braces makes sense.

**Comment by ahwillia** [comment]
> I highlight something as a type if I can detect that it is a type. It obviously gives an inconsistency . What do we think of this?

I'm having a slight change of heart on this. Would it be possible to detect the main types that are in Base? It seems like you could in principle highlight the following:

<img width="200" alt="screen shot 2016-08-13 at 12 40 39 pm" src="https://cloud.githubusercontent.com/assets/636625/17645197/33c19984-6153-11e6-9685-dcdcd1ece439.png">

Really, really appreciate all the work you've been putting into this. 👍

**Comment by ViktorQvarfordt** [comment]
I agree. I just pushed a fix for this.

![image](https://cloud.githubusercontent.com/assets/344809/17645736/5cdd7706-61ae-11e6-8c19-8878d850e92f.png)

I don't know if I found all base exported types. There is no easy way to get a list of all types. Let me know if I missed any. It is also easy to add to `Julia.sublime-syntax`, this is on line [21](https://github.com/JuliaEditorSupport/Julia-sublime/blob/develop/Julia.sublime-syntax#L21).

(In principle it is possible to highlight user defined types by parsing the file for `type ...` and then dynamically creating a special dynamic syntax file. This is borderline insane, given that sublime text has no API for interfacing the syntax scopes. I've seen this done in "semantic highlighting".)

**Comment by ViktorQvarfordt** [comment]
Are we happy with the string interpolation? Am I correct in only highlighting interpolation for un-prefixed `"` and `"""` strings?

If no one objects, I'm considering merging this into master. Frankly, `develop` is in a much better state than `master`.

**Comment by ahwillia** [comment]
I haven't had any problems with string interpolation. +1 for merging into
master.

**Comment by ViktorQvarfordt** [comment]
Thanks for all your input guys! It turned out much better than if I had done it all by myself.

New issues, pull requests and suggestions for further improvement are always welcome.
