### ISSUE TITLE
println("sqrt(4) = 2") messes up the new syntax highlighting

### ISSUE THREAD

**Issue by PaulSoderlind** [JuliaEditorSupport/Julia-sublime#25]
Hi,
and thanks for your efforts to improve the julia/sublime cooperation.

I've noticed that the newest version (v2016.08.14...) causes some problems on my Win7 machine. 
For instance, the lines
```
println("sqrt(4) = 2")
a0 = 1
```
show everything from 2 and onward in red (string, I think).

Btw. the Julia package seems to update itself. Why is that?

Best, Paul S

**Comment by ViktorQvarfordt** [comment]
Oops! know why, will fix soon. Thanks for reporting this!

**Comment by ViktorQvarfordt** [comment]
Package control updates all your packages each time sublime starts. Do you mean that the Julia package behaves different to other packages in some way?

**Comment by PaulSoderlind** [comment]
>Oops! know why, will fix soon. Thanks for reporting this!
Thanks. 
> Do you mean that the Julia package behaves different to other packages in some way?
No, you're right. I just forgot that.
