### ISSUE TITLE
Colored whitespace after function keyword

### ISSUE THREAD

**Issue by fredrikekre** [JuliaEditorSupport/Julia-sublime#26]
If the setting to draw white space is turned on in sublime (`"draw_white_space": "selection"` or `"draw_white_space": "all"`) the space-dot after `function` is colored with the same color as the `function` keyword.
Here the dot is red:
![reddot](https://cloud.githubusercontent.com/assets/11698744/17772591/f26f50de-6549-11e6-8a8a-8c7dd8460f79.png)

**Comment by ViktorQvarfordt** [comment]
I had not thought about whitespaces. This is now fixed. Thanks for reporting!

**Comment by fredrikekre** [comment]
Works fine on other similar keywords, such as `type` and `immutable`. This was the only thing I found.

**Comment by ViktorQvarfordt** [comment]
The parsing of function declarations is more complex than the rest, whence it is handled separately and this small bug could sneak in.

**Comment by fredrikekre** [comment]
Aight, thanks for the fix!
