### ISSUE TITLE
Broken multiline regex syntax highlighting

### ISSUE THREAD

**Issue by Michael-Klassen** [JuliaEditorSupport/Julia-sublime#28]
The `$` at the end of a regex with triple quotes breaks the syntax highlighting.
```julia
r"\n a \" b $"x  # Works.
r"""\n a \" b $"""x  # Broken.

print("""Hello World""")  # Messed up.
```
The `$` makes the syntax highlighter think `"""x` is a variable so the multiline string doesn't end.

**Comment by ViktorQvarfordt** [comment]
Thanks for reporting this issue! This is now fixed.

(I had previously forgotten to take care of triple-quoted regex strings. The triple quoted regex string was previously parsed as an ordinary string and the dollar sign was parsed as a string interpolation.)
