### ISSUE TITLE
Triple quote strings

### ISSUE THREAD

**Issue by fredrikekre** [JuliaEditorSupport/Julia-sublime#29]
This is a somewhat bizarre case I found while viewing [this](https://github.com/JuliaLang/IJulia.jl/blob/master/deps/build.jl#L146) in sublime. Seems to be that a double quote (") can end a triple quote (""") segment, but only if string interpolation is used within the string.
![longstring](https://cloud.githubusercontent.com/assets/11698744/17998109/fe25eb98-6b72-11e6-806b-45b3a873e2fc.png)

**Comment by fredrikekre** [comment]
Connected to #28 I assume.

**Comment by ViktorQvarfordt** [comment]
Thanks for reporting this! It is now fixed.

(It was an obvious mistake from my end. Previously, when string interpolation was done, the parser jumped back to an ordinary string, regardless of whether we started in a triple-quoted string or not.)
