### ISSUE TITLE
Use of = in a string

### ISSUE THREAD

**Issue by fredrikekre** [JuliaEditorSupport/Julia-sublime#30]
Using = in a string for calling a function with a parenthesis makes the parser believe it is a function definition instead of a function call.

<img width="289" alt="screen shot 2016-08-26 at 16 14 29" src="https://cloud.githubusercontent.com/assets/11698744/18008391/320a4712-6ba8-11e6-9987-fe35a054d95e.png">

**Comment by ViktorQvarfordt** [comment]
Thanks! Fixed.
