### ISSUE TITLE
Optional arguments sometimes cause highlighting issues

### ISSUE THREAD

**Issue by ahwillia** [JuliaEditorSupport/Julia-sublime#31]
The first line below looks good, but the `z` in the second line should be orange. <s>I think the problem generally occurs when you call a function (here the constructor `MyType()`) while defining default values.</s> *(Not so sure about this anymore, see below)*

<img width="348" alt="screen shot 2016-08-27 at 4 02 05 pm" src="https://cloud.githubusercontent.com/assets/636625/18030583/aa0edddc-6c6f-11e6-9abb-512ab7005781.png">

**Comment by ahwillia** [comment]
Update, the semicolon is perhaps the cause of the problem?

Without semicolon:

<img width="369" alt="screen shot 2016-08-27 at 4 08 49 pm" src="https://cloud.githubusercontent.com/assets/636625/18030603/acac6842-6c70-11e6-848b-64a5e33f374e.png">

With semicolon:

<img width="297" alt="screen shot 2016-08-27 at 4 10 18 pm" src="https://cloud.githubusercontent.com/assets/636625/18030606/c7c9d380-6c70-11e6-8e1c-9b699503a91c.png">

**Comment by ViktorQvarfordt** [comment]
This was indeed because of the semicolon. Fixed. Thanks!
