### ISSUE TITLE
Interpolation not highlighted in Cmd strings

### ISSUE THREAD

**Issue by ahwillia** [JuliaEditorSupport/Julia-sublime#32]
This one should be simple to fix?

<img width="155" alt="screen shot 2016-08-29 at 12 32 40 pm" src="https://cloud.githubusercontent.com/assets/636625/18064564/d38b0d4a-6de4-11e6-9860-e35d766cebe9.png">

**Comment by ViktorQvarfordt** [comment]
Indeed, thanks for this!
