### ISSUE TITLE
Functions without arguments are highlighted differently

### ISSUE THREAD

**Issue by ahwillia** [JuliaEditorSupport/Julia-sublime#36]
<img width="139" alt="screen shot 2016-08-31 at 6 58 37 pm" src="https://cloud.githubusercontent.com/assets/636625/18152744/120a95f8-6fad-11e6-9f49-cf35c1eb497c.png">

**Comment by fredrikekre** [comment]
Duplicate of #33 and also this was fixed in 689752e

**Comment by ahwillia** [comment]
Weird I must not have the latest then. Sorry for the noise!

**Comment by ViktorQvarfordt** [comment]
Rather noise than bugs :)
