### ISSUE TITLE
Highlighting numbers with underscores

### ISSUE THREAD

**Issue by ahwillia** [JuliaEditorSupport/Julia-sublime#37]
This is handy to use sometimes:

<img width="56" alt="screen shot 2016-09-02 at 6 54 56 pm" src="https://cloud.githubusercontent.com/assets/636625/18222006/e2f43ccc-713e-11e6-91d0-b264e4697c17.png">

**Comment by ViktorQvarfordt** [comment]
Thanks, fixed! Hopefully we have all number literals covered now, see the [tests](https://github.com/JuliaEditorSupport/Julia-sublime/blob/master/syntax_test_julia.jl#L9).
