### ISSUE TITLE
Not equal to operator != 

### ISSUE THREAD

**Issue by fredrikekre** [JuliaEditorSupport/Julia-sublime#38]
This should be parsed as "a not equal to 4" and not as assignment of 4 to variable `a!`
![fail](https://cloud.githubusercontent.com/assets/11698744/18385477/32a69470-7691-11e6-8a80-826c73905783.png)

**Comment by ViktorQvarfordt** [comment]
I don't think this can be solved in a consistent manner. Consider how you'd highlight the following code.

```
a! = 3
b = 3
if a!=4  ... end  # ERROR: UndefVarError: a not defined
if b!=4  ... end  # ok
if a!!=4 ... end  # ok
if b!!=4 ... end  # ERROR: UndefVarError: b! not defined
```

Personally I think this is an ugly part of Julia. My recommendation is to use spaces between your infix operators (when ambiguities can arise).

**Comment by fredrikekre** [comment]
Oh well, that's a bit weird. I'm using spaces anyway :p

**Comment by ViktorQvarfordt** [comment]
Closing this. Please reopen if you find some way of fixing this!
