### ISSUE TITLE
Wrong LaTeX completion

### ISSUE THREAD

**Issue by andreasnoack** [JuliaEditorSupport/Julia-sublime#42]
I'm using Sublime Text 3 build 3126 on macOS Sierra. When I execute `\mu`+`[tab]` I get `𝑈`. I haven't noticed any other problems with completion and it works in the REPL.

**Comment by ViktorQvarfordt** [comment]
This is an error with the the unicode completions, with is included from [UnicodeCompletion](https://github.com/randy3k/UnicodeCompletion) by @randy3k. Could you take a look at this, @randy3k?

**Comment by randy3k** [comment]
It is not a bug of Julia-sublime or UnicodeCompletion per se. It is an issue of Sublime-Text. If the auto complete menu is shown, the <tab> key will always send the current chosen word. There are 2 solutions.

1. after typing `\mu`, select `μ` and <tab>. Sublime will remember your choice next time you type `\mu`

2. after typeing `\mu`, press <esc> before pressing <tab>. It will hide the auto complete menu, so the exact match will be used.

**Comment by andreasnoack** [comment]
Ah. I didn't know that. Thanks for explaining.
