### ISSUE TITLE
Indentation increases don't happen if the increaseIndentPattern is preceded by any non-whitespace characters

### ISSUE THREAD

**Issue by iamed2** [JuliaEditorSupport/Julia-sublime#44]
If one types <kbd>TAB</kbd> `begin` <kbd>ENTER</kbd> `3` <kbd>ENTER</kbd> `end`, one gets:
```julia
    begin
        3
    end
```
but if one types <kbd>TAB</kbd> `1 + begin` <kbd>ENTER</kbd> `3` <kbd>ENTER</kbd> `end`, one gets:
```julia
    1 + begin
    3
end
```

This occurs commonly when writing e.g., macros which take block arguments.

**Comment by ViktorQvarfordt** [comment]
We currently have

```
<key>decreaseIndentPattern</key>
<string>^\s*(end|else|elseif|catch|finally).*$</string>

<key>increaseIndentPattern</key>
<string>^\s*(if|else|elseif|for|while|begin|function|type|macro|immutable|try|catch|finally|let|quote|do).*$</string>
```

in https://github.com/JuliaEditorSupport/Julia-sublime/blob/master/Indentation.tmPreferences.

Note the `^\s*`, i.e. `begin` cannot be preceded by non-space characters in order to trigger auto-indent. One could of course remove `^\s*`, but this might open up for problems such as auto-indent being triggered if you type 'begin' in a string.

What do you think about this?

**Comment by iamed2** [comment]
I looked at Ruby because it has a similar syntax. They go all in:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Indent</string>
	<key>scope</key>
	<string>source.ruby</string>
	<key>settings</key>
	<dict>
		<key>decreaseIndentPattern</key>
		<string>^\s*([}\]]\s*$|(end|rescue|ensure|else|elsif|when)\b)</string>
		<key>increaseIndentPattern</key>
		<string>(?x)^
		(\s*
			(
				module|class|def
				|unless|if|else|elsif
				|case|when
				|begin|rescue|ensure
				|for|while|until
				|
				(?=.*? \b(do|begin|case|if|unless)\b )
				# the look-ahead above is to quickly discard non-candidates
				(
					"(\\.|[^\\"])*+"      # eat a double quoted string
					| '(\\.|[^\\'])*+'    # eat a single quoted string
					| [^#"']              # eat all but comments and strings
				)*
				(
					\s   (do|begin|case)
					| [-+=&amp;|*/~%^&lt;&gt;~](?&lt;!\$.) \s*+ (if|unless)
				)
			)\b
			(?! [^;]*+ ; .*? \bend\b )
			|
			(
				"(\\.|[^\\"])*+"          # eat a double quoted string
				| '(\\.|[^\\'])*+'        # eat a single quoted string
				| [^#"']                  # eat all but comments and strings
			)*
			(
				\{ (?!  [^}]*+ \} )
				| \[ (?! [^\]]*+ \] )
			)
		).*$
		</string>
	</dict>
</dict>
</plist>
```

**Comment by iamed2** [comment]
Another option that wouldn't exactly fix this but would fix my case would be to have a snippet for begin-end, if-end, etc. that would mimic the behaviour of `{}` in e.g., C. `begin` snippet would generate `begin  end` with the cursor in the middle, and then pressing <kbd>ENTER</kbd> would expand to (using my example as a template):
```julia
    1 + begin
        # cursor here
    end
```

**Comment by ViktorQvarfordt** [comment]
Woah, looks interesting. I don't have time to look at this now. If you want, feel free to tweak the ruby version to work with Julia and submit at pull request. Regarding the snippet, you can add that manually, I don't think that should be part of the package.

Although, perhaps it would be nice to have snippets for all syntax that contains mandatory closing words (such as begin-end, if-end, while-end etc.). What do you think about this? Perhaps it would be annoying, perhaps one often re-writes code and types `begin` while `end` is already inserted, this would cause double `end`s...

**Comment by ViktorQvarfordt** [comment]
I feel discouraged from adding indentation regex similar to Ruby (it's quite messy, I prefer simplicity). I've changed my mind regarding a snippet for begin, it's a splendid idea that fixes this issue. I've pushed commit 54f5325d7bcb8c2a38bd6db5cc19c8e1a8b06959 which adds such a snippet.

Feel free to reopen this issue, or open new ones if you feel anything can be improved.

**Comment by iamed2** [comment]
Works like a charm, thanks :)

I love the turnaround on Sublime package releases! I could just update within the editor with no fuss.
