### ISSUE TITLE
julia highlight is not coherent with other language syntaxes

### ISSUE THREAD

**Issue by randy3k** [JuliaEditorSupport/Julia-sublime#46]
- [x] don't highlight variables
- [x] regular function call should be `variable.function` only and the arguments should be `meta.function-call.arguments variable.parameter`
- [x] supported function should be `support.function` only and parameters should be `meta.function-call.arguments variable.parameter`.

![screen shot 2017-03-22 at 5 30 29 pm](https://cloud.githubusercontent.com/assets/1690993/24224389/4decf024-0f31-11e7-8253-5843a93f068d.png)

** Updated screenshot for julia**

![screen shot 2017-03-22 at 6 55 56 pm](https://cloud.githubusercontent.com/assets/1690993/24224382/3e794408-0f31-11e7-82b6-2fe7c6bd260a.png)

**Comment by ViktorQvarfordt** [comment]
Thanks! However, something is not right... Are you not using the latest version?

- Variables works fine
![image](https://cloud.githubusercontent.com/assets/344809/24222580/d79d1c2e-0f52-11e7-90e3-6dc68ef299c1.png)
- Function declaration works fine
![image](https://cloud.githubusercontent.com/assets/344809/24222487/9a481c0c-0f52-11e7-8174-f47c1a237496.png)
![image](https://cloud.githubusercontent.com/assets/344809/24222667/1bdd2f5a-0f53-11e7-8158-f151ee638acf.png)
- Function calls; currently all function calls have `support.function`
![image](https://cloud.githubusercontent.com/assets/344809/24222695/3b05a380-0f53-11e7-9bdc-9a0a758b1812.png)
see the comment https://github.com/JuliaEditorSupport/Julia-sublime/blob/master/Julia.sublime-syntax#L138.
Furthermore, arguments have no particular scope, I agree this should be fixed.
![image](https://cloud.githubusercontent.com/assets/344809/24222734/5f47f90a-0f53-11e7-9efa-e23209dffc9b.png)

I'm open for discussion regarding `support.function`, I have function calls highlighted for all languages in my color scheme. I'm okay with removing `support.function` for all function calls. However, I'd need a list of what functions calls to give the scope `support.function`. (Personally I think it is weird to distinguish between some function calls and others, but that's personal opinion and I disregard that. Consistency across languages is important.)

I realize, perhaps you are using an old version of sublime text, from the readme:

> Sublime Text 3 Build 3103 or later will use Julia.sublime-syntax which provides superior highlighting. For backward compatibility Julia.tmLanguage acts as fallback.

If you could be a bit more specific, I can implement a fix more easily. Ideally you could write some failing tests in https://github.com/JuliaEditorSupport/Julia-sublime/blob/master/syntax_test_julia.jl.

**Comment by randy3k** [comment]
Stupid me. I forgot to pull the latest commits and it does fix some of the issues.
However, for the regular variables, they should not be matched, even for `variable.other`. At least it is how python and r behave.

Check the updated list above.

**Comment by randy3k** [comment]
> I have function calls highlighted for all languages in my color scheme

If you want to the same coloring for both supported functions and general functions, you just need to edit your color scheme and modify the color for the scope `variable.other`. However, it will affect all other languages such as python and r.

**Comment by ViktorQvarfordt** [comment]
1. We should really distinguish between setting scopes (determined by this package) and how scopes are highlighted (determined by color schemes). However, it is reasonable to make sure that the default color scheme looks good.

2. Regarding `variable.other`, there is already an inconsistency across default languages here, javascript adds this scope:
![image](https://cloud.githubusercontent.com/assets/344809/24240199/0ad02b1e-0fb1-11e7-9c06-419ba97a0fe3.png)
The default color schemes does nothing with `variable.other` and I think it is good to add this scope, so that plugins and color schemes can track variables. You probably want to look over your particular color scheme.

3.
    > **regular function call should be variable.function only and the arguments should be meta.function-call.arguments** variable.parameter

    Bold part yes, I have fixed this now, in commit cc2b8de2198a81510eb0450eba2e3d2dce12b05b, so that only built-in functions have `support.function` and all functions have `variable.function`, function calls have `meta.function-call` and function call arguments have `meta.function-call.arguments`. However, note that not all languages add `meta.function-call.arguments` to function call arguments, JavaScript does not add this scope:
![image](https://cloud.githubusercontent.com/assets/344809/24243130/42648f9e-0fba-11e7-8b85-02b377608a6d.png)


    > regular function call should be variable.function only and the arguments should be meta.function-call.arguments **variable.parameter**

    Bold part no? `variable.parameter` is for arguments in function declaration only. For example, Python has these scopes
    ![image](https://cloud.githubusercontent.com/assets/344809/24240383/a763b8d8-0fb1-11e7-8b77-2693ac43d782.png)

With this I consider all items in your list checked. Do you agree?

**Comment by randy3k** [comment]
I guess we need to be more specific, I meant the variable name but not the value of the variable. Python uses `variable.parameter` for the variable name.

```
foo(x = y)
#   ^ variable.parameter
```

**Comment by randy3k** [comment]
Though you mention that Javascript also uses `variable.other`, a lot of Julia users are more familiar to Python then JS. It seems that it makes sense to follow the convention of Python/C/Ruby, etc.  

Besides, if one's color scheme highlights `variable.other`, the emojis are also highlighted and it is less satifactory.
![screen shot 2017-03-23 at 3 33 09 pm](https://cloud.githubusercontent.com/assets/1690993/24266720/3c56b14e-0fde-11e7-9353-bb304004ceec.png)

WIth that said, I respect your any decision on this issue.

**Comment by ViktorQvarfordt** [comment]
I mostly agree, will look into this more, but first, when is `variable.other` supposed to be used, if not for plain variables? Why do you highlight `variable.other`?

**Comment by randy3k** [comment]
From [here](https://github.com/sublimehq/Packages), I have gathered the list of usages,

- Regular variables
   - ASP, C#, GO, JavaScript, PHP

- Special variables
   - C++: initialization list
   - Lisp: global variables
   - Python: placeholder variable `"%s"`
   - Ruby: constant variable
   - YAML

All other syntaxes either do not use `variable.other` or those are the syntaxes which I don't have much exposure.

I am using a variation of https://github.com/jonschlinkert/sublime-monokai-extended which highlights `variable.other`. Given the [popularity](https://packagecontrol.io/packages/Monokai%20Extended) of this theme, it is another strong reason for not highlighting variables.

**Comment by randy3k** [comment]
I notice that only functions in `Base` module are exported. The functions in `Core` module should be also considered.

**Comment by ViktorQvarfordt** [comment]
Thanks for that overview, I was about to change my mind based on this, until I found the [official docs](https://www.sublimetext.com/docs/3/scope_naming.html#variable), according to which `variable.other` is supposed to be used like we do in this package. In light of this, what do you think regarding `variable.other`?

I was not aware of this documentation for scopes, perhaps we find more things that should be changed to follow these guidelines.

I agree with you regarding `variable.parameter`. This is now fixed in https://github.com/JuliaEditorSupport/Julia-sublime/commit/6a56ed3e5b5a81704cfb8770f29805d88ba9a7d3. 

> I notice that only functions in Base module are exported. The functions in Core module should also be considered.

This is now fixed in https://github.com/JuliaEditorSupport/Julia-sublime/commit/3ea5262a69f1ba2d2b237c5e5e265f1fd2134740.

**Comment by randy3k** [comment]
Great. I agree that we should keep `variable.other`. The solution for me now would be to modify my color scheme. Anyway, thanks for your responsive work!

**Comment by ViktorQvarfordt** [comment]
Sweet. Thanks for your constructive input!
