### ISSUE TITLE
Number after `e`

### ISSUE THREAD

**Issue by fredrikekre** [JuliaEditorSupport/Julia-sublime#51]
The combination of `e` and a number seem to be incorrectly highlighted? Does not happen with other letters, this probably happens because `e` on its own is highligted as the constant? 

![screenshot from 2017-04-25 08-51-25](https://cloud.githubusercontent.com/assets/11698744/25372136/6274ebb4-2994-11e7-973b-f4b16f5401c4.png)

**Comment by fredrikekre** [comment]
Also this:
![screenshot from 2017-04-25 08-52-52](https://cloud.githubusercontent.com/assets/11698744/25372193/9ae45872-2994-11e7-8219-2dba0fca64bd.png)

**Comment by ViktorQvarfordt** [comment]
Thanks! There was an issue with parsing of scientific notation, this is now fixed. (The corresponding tests are [here](https://github.com/JuliaEditorSupport/Julia-sublime/blob/master/syntax_test_julia.jl#L48).)

**Comment by fredrikekre** [comment]
Thanks!
