### ISSUE TITLE
mutable struct no highlighted in snippet 

### ISSUE THREAD

**Issue by musm** [JuliaEditorSupport/Julia-sublime#52]
![image](https://cloud.githubusercontent.com/assets/4319522/25440610/f7230a1e-2a6d-11e7-844c-e5f5d4b7c0ad.png)

**Comment by ViktorQvarfordt** [comment]
This was an issue with `$` not parsed properly in type names in type constructors. Fixed now.

I realize that we might have similar issues with `$` in other places, not sure..
