### ISSUE TITLE
typealias highlighting issues

### ISSUE THREAD

**Issue by musm** [JuliaEditorSupport/Julia-sublime#53]
![image](https://cloud.githubusercontent.com/assets/4319522/25458677/d76c86f6-2aa8-11e7-8d06-204bbbabd0d2.png)

**Comment by musm** [comment]
ops I just realize this is probably becaause of newline character

**Comment by ViktorQvarfordt** [comment]
Indeed, at the moment no types can span multiple lines. However, It can be fixed. I'll do that some time, so I reopen this.

**Comment by musm** [comment]
stale
