### ISSUE TITLE
Unicode completion

### ISSUE THREAD

**Issue by matthieugomez** [JuliaEditorSupport/Julia-sublime#56]
Would it be possible to have Unicode completion in the search window? (i.e. the window that appears after CMD+F)

**Comment by ViktorQvarfordt** [comment]
I think so. But unicode completion would then have to be enabled in the scope of that input field, currently it is enabled only for `source.jl`. Perhaps @randy3k knows more. See also https://github.com/randy3k/UnicodeCompletion for using unicode completion in other scopes etc. 

(If you are using Linux, this might be of interest https://github.com/ViktorQvarfordt/xkb-unicode-input/ (unicode input as an extended keyboard layout and compose keys, for use in any application).)

**Comment by randy3k** [comment]
Unicode Completion is [disabled](https://github.com/randy3k/UnicodeCompletion/blob/f9c3f8961fb9afbe94a8c82615c59b3c735c6e59/unicode_completion.py#L14-L14) by default for widgets. It should not cause any issues if we remove these lines.

**Comment by ViktorQvarfordt** [comment]
I'm ok with this.

**Comment by matthieugomez** [comment]
Good, it would be nice to enable it for widgets.
If I understand you correctly, you're saying completion in a search window will never work with a solution based on Julia specific scope? 
If this is the case, I'm not sure it's a good idea to have a UnicodeCompletion-with-Julia-scope in this package. It would be better to include either nothing or the whole UnicodeCompletion package with this package.

**Comment by randy3k** [comment]
Not really, it just need some changes. Check #57.

**Comment by matthieugomez** [comment]
Awesome! Thank you so much 👍
