### ISSUE TITLE
A Pair{Symbol, _} literal in a function call is highlighted as a keyword argument

### ISSUE THREAD

**Issue by iamed2** [JuliaEditorSupport/Julia-sublime#58]
Test:
```julia
foo(bar, :baz=>3)
```

In my Sublime:

[Screenshot](https://www.dropbox.com/s/1nzzppprhlvjjjc/Screenshot%202017-07-06%2015.11.33.png?dl=0)

**Comment by ViktorQvarfordt** [comment]
Something fishy in the regex that parses function calls. Unfortunately, I don't have time to look at this. However, you are very welcome to submit a pull request with a fix.
