### ISSUE TITLE
Automatic indentation after specific keywords

### ISSUE THREAD

**Issue by bkamins** [JuliaEditorSupport/Julia-sublime#59]
I have trouble with indentation of code using `struct`, `mutable struct` and `do`.
Sublimetext does not indent the line following one of those keywords. The first two seem to be undefined in indentation but `do` is defined but does not trigger indentation.

**Comment by ViktorQvarfordt** [comment]
Unfortunately, I don't have time to look at this. However, you are very welcome to submit a pull request with a fix.
