### ISSUE TITLE
blank function with newline breaks highlighting below

### ISSUE THREAD

**Issue by iamed2** [JuliaEditorSupport/Julia-sublime#60]
Reality:
<img width="88" alt="screenshot 2017-07-28 11 27 24" src="https://user-images.githubusercontent.com/3131001/28726736-09c097aa-7388-11e7-9354-d4b5788db97f.png">

Ideal:
<img width="94" alt="screenshot 2017-07-28 11 30 33" src="https://user-images.githubusercontent.com/3131001/28726786-33b08778-7388-11e7-981a-01834817c093.png">

Note: the first doesn't happen if the `end` was initially higher up and was moved down, or if the function definition at one point had parens.

**Comment by ViktorQvarfordt** [comment]
Looks like the regex that parses function declaration requires a function body. Should be an easy fix. Unfortunately, I don't have time to look at this. However, you are very welcome to submit a pull request with a fix.

**Comment by iamed2** [comment]
Thanks for the responses :)
