### ISSUE TITLE
Indentation broken after one-line for..end and if..end blocks

### ISSUE THREAD

**Issue by albertas-jn** [JuliaEditorSupport/Julia-sublime#61]
Indentation is broken after one-line for..end and if..end blocks. "Reindent Lines" results in this:
```
function func(n)
    a = 0
    for i in 0:n a = a + i; end
        return a
    end
```
Last two lines are over-indented. Same for if...end.
***
Sublime Text 3.0,  Julia-sublime 2017.08.25.20.37.31

**Comment by ViktorQvarfordt** [comment]
Indeed, there is an issue with keywords triggering indent (`for`) and keywords triggering unindent (`end`) occurring on the same line. Unfortunately, I don't have time to look at this. However, you are very welcome to submit a pull request with a fix.
