### ISSUE TITLE
Highlighting of function input

### ISSUE THREAD

**Issue by fredrikekre** [JuliaEditorSupport/Julia-sublime#62]
Input to functions are highlighted as for function *definitions*
![screenshot from 2017-11-02 12-04-25](https://user-images.githubusercontent.com/11698744/32322837-34ab6294-bfc6-11e7-9e8a-e22796b962a0.png)

**Comment by ViktorQvarfordt** [comment]
Probably an issue [here](https://github.com/JuliaEditorSupport/Julia-sublime/blob/master/Julia.sublime-syntax#L245) in the code. You could make a PR if you fix it.
