### ISSUE TITLE
Some explanation on how the package works is needed

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaEditorSupport/Julia-sublime#76]
I have to admit I haven't figured out how this package works. I could find neither Julia.sublime-syntax, nor Julia.tmLanguage anywhere under the Sublime Text folder for settings.

Where DOES the knowledge of Julia syntax come from then? Would you please enlighten me? Also for the sake of those who might wish to tweak things that they feel need changing.

**Comment by ViktorQvarfordt** [comment]
https://github.com/JuliaEditorSupport/Julia-sublime/blob/master/Julia.sublime-syntax

**Comment by PetrKryslUCSD** [comment]
Thank you. I can certainly see that the file is in the repo. However I couldn't find it in the `AppData\Roaming\Sublime Text 3\Packages\` installation folder on my computer. In fact I couldn't find ANY file that could be identified with the Julia-sublime package. How is this package installed?

**Comment by PetrKryslUCSD** [comment]
Got it. It is .sublime-package.

**Comment by ViktorQvarfordt** [comment]
I see, I misunderstood your question. Glad you found it!
