### ISSUE TITLE
There is no such thing as Sublime Text 4

### ISSUE THREAD

**Issue by lewisl** [JuliaEditorSupport/Julia-sublime#87]

**Comment by musm** [comment]
I was wondering the same

**Comment by jwortmann** [comment]
Beta versions of ST 4 (requiring a license) are available from the ST Discord server. There is an inofficial changelog at https://gist.github.com/jfcherng/7bf4103ea486d1f67b7970e846b3a619.

**Comment by lewisl** [comment]
Well, there is now!
