### ISSUE TITLE
Please add a license to the repo

### ISSUE THREAD

**Issue by niclasmattsson** [JuliaEditorSupport/Julia-sublime#88]
I hope the lack of license is just an oversight. Please add one ASAP, or at least explain why there is none.

**Comment by randy3k** [comment]
@ViktorQvarfordt, you were the author, please specify a license :)

**Comment by rvantonder** [comment]
Would also appreciate if this project had a license!

**Comment by ViktorQvarfordt** [comment]
Done!

https://github.com/JuliaEditorSupport/Julia-sublime/blob/master/LICENSE

**Comment by rvantonder** [comment]
Thank you!
