### ISSUE TITLE
Bug in recognition of single quote

### ISSUE THREAD

**Issue by lewisl** [JuliaEditorSupport/Julia-sublime#89]
This syntax always treats single quote as the opening of a char. 

A single quote can also mean transpose of a matrix--a unary operator post fix.

The parser needs to have an additional rule: if a single quote is not followed by a SINGLE character and another single quote then the transpose usage is in effect.

I see the error as most of a file is highlighted in red after a single quote because the closing single quote is not found. This occurs when the single quote means transpose a matrix.

I should not have to change my code to the function for transpose to defeat the syntax highlighter.

Note that the older version of Julia-sublime didn't have this error,.

**Comment by lewisl** [comment]
I found that I can install the old version for 2/3 and it works fine with 4.0 beta.  Not sure why there is another version. Be nice to have one that works for 3/4 (seems like you can drop 2 although some users may not have wanted to pay for the Sublime Text 3.0 upgrade).

**Comment by randy3k** [comment]
Hi @lewisl , could you provide an example?

**Comment by lewisl** [comment]
This is fixed--probably some time ago.
