### ISSUE TITLE
Syntax highlighting breaks with anonymous functions in arg list

### ISSUE THREAD

**Issue by charleskawczynski** [JuliaEditorSupport/Julia-sublime#93]
I'm not sure if this is the correct repo to post this issue, so please let me know if it should be posted elsewhere. I've noticed that syntax highlighting seems to break when using anonymous functions inside an argument list, the same is true for positional args and kwargs. Here's a screenshot example:

![image](https://user-images.githubusercontent.com/1880641/97089202-20fecf00-15eb-11eb-83ea-6c6403592b53.png)

**Comment by randy3k** [comment]
Are you using Sublime Text 3? It should be fixed in Sublime Text 4.

**Comment by musm** [comment]
Where exactly do you obtain this mythical version of sublime text? 

I only see version 3:
https://www.sublimetext.com/3
https://www.sublimetext.com/3dev

**Comment by charleskawczynski** [comment]
I see this on Sublime Text 3, Version 3.2.2, Build 3211.

**Comment by randy3k** [comment]
It's a beta testing phase. You could download it from the official discord server. However you will need a proper license to activate it.

**Comment by charleskawczynski** [comment]
@randy3k can you share a link?

**Comment by randy3k** [comment]
> @randy3k can you share a link?

It could be easily googled. 
https://discord.gg/D43Pecu

**Comment by randy3k** [comment]
fixed in 1.0.2+.
