### ISSUE TITLE
Definition / goto is broken for function arguments with multiple lines

### ISSUE THREAD

**Issue by charleskawczynski** [JuliaEditorSupport/Julia-sublime#96]
It seems that when functions are defined with arguments written across multiple lines, Julia-sublime fails to capture the definition (and therefore `goto` also misses the definition). Here are some screenshot examples:

Listed definitions / references
![DefinitionFails](https://user-images.githubusercontent.com/1880641/107887732-0368b480-6ebd-11eb-9545-be705c91b7ca.png)

Go-to drop-down
![GoToFails](https://user-images.githubusercontent.com/1880641/107887735-0663a500-6ebd-11eb-8795-17b83a97b48e.png)

**Comment by charleskawczynski** [comment]
Update: it looks like the go-to drop-down options are fixed in Build 4107, but the listed definitions still misses the last definition.

**Comment by randy3k** [comment]
It doesn't seem that you are using the latest version of Julia. Please double check.

**Comment by charleskawczynski** [comment]
Do you mean the latest version of Julia-sublime?

**Comment by randy3k** [comment]
Yes

**Comment by charleskawczynski** [comment]
I'm using Julia-sublime v1.05. Isn't that the latest release?

**Comment by randy3k** [comment]
Yes. And it should be working perfectly.

<img width="807" alt="Screen Shot 2021-06-23 at 3 14 44 PM" src="https://user-images.githubusercontent.com/1690993/123174966-d792a800-d435-11eb-9af8-08996a95cb55.png">

**Comment by charleskawczynski** [comment]
I see the same behavior as what your showing, but my example still breaks (because of the line breaks in the argument list).

**Comment by randy3k** [comment]
Still works for me.
![Screen Shot 2021-06-23 at 5 29 08 PM](https://user-images.githubusercontent.com/1690993/123184429-893ad480-d448-11eb-99e5-fcd8c70551b9.png)

**Comment by charleskawczynski** [comment]
> Yes. And it should be working perfectly.

Ah, sorry, the problem is with the definition list, not the go-to. So, using go-to seems to work fine, but hovering over `foo` will miss the 
```julia
foo(
     ::Int,
     ::String,
) = foo("1")
```
_definition_ (it will display the reference).

**Comment by randy3k** [comment]
It also works.
![Screen Shot 2021-06-24 at 8 45 45 PM](https://user-images.githubusercontent.com/1690993/123366494-2b33ed00-d52d-11eb-8100-35a2af7a2782.png)

**Comment by charleskawczynski** [comment]
Interesting. The example you showed is _still_ different from my original one. I'm hovering over a definition, and you're hovering over a reference below.

<img width="576" alt="Screen Shot 2021-06-28 at 10 32 58 AM" src="https://user-images.githubusercontent.com/1880641/123679441-556efe80-d7fc-11eb-8be8-fd646fd9592f.png">

<img width="571" alt="Screen Shot 2021-06-28 at 10 33 21 AM" src="https://user-images.githubusercontent.com/1880641/123679448-5738c200-d7fc-11eb-9318-6126c364ad5e.png">

**Comment by randy3k** [comment]
Of course, it doesnt show the definition at lone 6 if you are hovering at the same line.

**Comment by charleskawczynski** [comment]
Ah, ok, thanks. I didn't know that was the expected behavior.
