### ISSUE TITLE
Release a new version for ST4

### ISSUE THREAD

**Issue by rwols** [JuliaEditorSupport/Julia-sublime#97]
In GitSavvy, I'm seeing this error: https://github.com/timbrel/GitSavvy/issues/1454

I was confused at first, because looking at the repo here there's no Julia.tmLanguage file. The reason is as follows. In the package control default channel this repo uses the "tags" system for ST builds >= 4000:

https://github.com/wbond/package_control_channel/blob/c201d2a98f849225286fcf998eb2a6483043c6bb/repository/j.json#L1306-L1309

My ST build is 4098. The last tag release was v1.0.0: https://github.com/JuliaEditorSupport/Julia-sublime/releases/tag/v1.0.0

Since that release the .tmLanguage file was removed. So, all that is needed to fix this error in GitSavvy is to make a new release in this repo :)

**Comment by randy3k** [comment]
Done. https://github.com/JuliaEditorSupport/Julia-sublime/releases/tag/v1.0.2

Sorry for the late reply (didn't subscribe this repo).
