### ISSUE TITLE
Vector transpose breaks highlighting

### ISSUE THREAD

**Issue by cossio** [JuliaEditorSupport/Julia-sublime#99]
When writing the tranpose of a vector with the notation `v'`, the syntax highlighter seems to be totally confused:

![image](https://user-images.githubusercontent.com/10637482/119482206-e2cdb780-bd53-11eb-89a8-ede4b66bb6ef.png)

I am on Sublime Text 4.

**Comment by jaakkor2** [comment]
Seems to work with v1.0.2.  I reproduce this on v1.0.3.

Pinging @randy3k , please note the breakage caused by v1.0.3 also in #100 .

**Comment by randy3k** [comment]
Thanks for reporting, I am on it.

**Comment by randy3k** [comment]
The original fix for #98 was not correct. Please check out v1.0.4
